# Generated by Django 6.0.3 on 2026-06-13 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encryption', models.BooleanField(default=True)),
                ('anonymization', models.BooleanField(default=True)),
                ('access_logs', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=30)),
                ('data_retention', models.IntegerField(default=365)),
                ('gdpr_compliant', models.BooleanField(default=True)),
                ('hipaa_compliant', models.BooleanField(default=True)),
                ('audit_frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], default='monthly', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de confidentialité',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_type', models.CharField(choices=[('admin', 'Administrateur'), ('doctor', 'Médecin'), ('hospital', 'Hôpital'), ('patient', 'Patient'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('action', models.CharField(choices=[('consultation', 'Consultation'), ('modification', 'Modification'), ('export', 'Export'), ('bulk_export', 'Export en masse'), ('deletion', 'Suppression'), ('access_denied', 'Accès refusé'), ('login', 'Connexion'), ('logout', 'Déconnexion')], max_length=30)),
                ('resource', models.CharField(choices=[('patient_data', 'Données patient'), ('patient_records', 'Dossiers patients'), ('reports', 'Rapports'), ('appointments', 'Rendez-vous'), ('prescriptions', 'Prescriptions'), ('system', 'Système')], max_length=30)),
                ('patient_id', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('access_request', "Demande d'accès"), ('deletion_request', 'Demande de suppression'), ('correction_request', 'Demande de correction'), ('portability_request', 'Demande de portabilité')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], default='pending', max_length=20)),
                ('data_requested', models.JSONField(default=list)),
                ('purpose', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
