# Generated by Django 6.0.3 on 2026-07-15 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('processing_fee', models.PositiveIntegerField(default=0)),
                ('net_amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('status', models.CharField(choices=[('completed', 'Complété'), ('pending', 'En attente'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('credit_card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], default='bank_transfer', max_length=20)),
                ('payment_type', models.CharField(choices=[('subscription', 'Abonnement'), ('consultation', 'Consultation'), ('other', 'Autre')], default='subscription', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('invoice_id', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('refunded', models.BooleanField(default=False)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('refund_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.hospital')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
