# Generated by Django 6.0.3 on 2026-07-23 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment_confirmed', 'Paiement confirmé'), ('call_started', 'Appel démarré'), ('appointment_confirmed', 'Rendez-vous confirmé'), ('appointment_cancelled', 'Rendez-vous annulé'), ('review_moderated', 'Avis modéré'), ('other', 'Autre')], default='other', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
