# Generated by Django 6.0.3 on 2026-07-15 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('doctor_specialty', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('video', 'Consultation vidéo'), ('in-person', 'En cabinet'), ('presentiel', 'Présentiel')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_call_type', models.CharField(blank=True, choices=[('video', 'Vidéo'), ('audio', 'Audio')], help_text="Préférence indicative du patient à la réservation — le médecin garde la main au moment de l'appel.", max_length=10, null=True)),
                ('call_type', models.CharField(blank=True, choices=[('video', 'Vidéo'), ('audio', 'Audio')], help_text="Vidéo ou audio, uniquement si type='video' (consultation en ligne)", max_length=10, null=True)),
                ('call_status', models.CharField(choices=[('none', 'Aucun appel'), ('waiting', 'En attente que le médecin démarre'), ('ongoing', 'Appel en cours'), ('ended', 'Appel terminé')], default='none', max_length=10)),
                ('call_room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token unique encodé dans le QR code du patient — jamais affiché en clair modifiable.', unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text="Horodatage de la confirmation d'arrivée par le personnel hospitalier.", null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, help_text="Membre du personnel (médecin ou compte hôpital) ayant confirmé l'arrivée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('consultation', 'Consultation de routine'), ('suivi', 'Consultation de suivi'), ('urgence', 'Urgence'), ('visite', 'Visite à domicile'), ('teleconsultation', 'Téléconsultation')], default='consultation', max_length=20)),
                ('motif', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('diagnostic', models.CharField(blank=True, max_length=255)),
                ('traitement', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'En cours'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=200)),
                ('duree', models.CharField(max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appointments.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('consultation_type', models.CharField(choices=[('consultation', 'Consultation'), ('urgence', 'Urgence'), ('video', 'Visioconférence'), ('chirurgie', 'Chirurgie')], default='consultation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.doctor')),
            ],
            options={
                'verbose_name': 'Disponibilité médecin',
                'verbose_name_plural': 'Disponibilités médecins',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
