# Generated by Django 6.0.3 on 2026-04-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('video', 'Consultation vidéo'), ('in-person', 'En cabinet'), ('presentiel', 'Présentiel')], max_length=20),
        ),
    ]
