# Generated by Django 6.0.3 on 2026-07-15 03:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compterendu',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="Token unique pour vérification publique d'authenticité (QR code).", unique=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="Token unique pour vérification publique d'authenticité (QR code).", unique=True),
        ),
    ]
