# Generated by Django 6.0.3 on 2026-05-12 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor'),
        ('appointments', '0002_alter_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_specialty',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
