# Generated by Django 6.0.3 on 2026-05-24 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hospital_registration_code'),
        ('appointments', '0005_prescription_prescriptionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('consultation', 'Consultation de routine'), ('suivi', 'Consultation de suivi'), ('urgence', 'Urgence'), ('visite', 'Visite à domicile'), ('teleconsultation', 'Téléconsultation')], default='consultation', max_length=20)),
                ('motif', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('diagnostic', models.CharField(blank=True, max_length=255)),
                ('traitement', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
