# Generated by Django 6.0.3 on 2026-07-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_compterendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='call_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='call_room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='call_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='call_status',
            field=models.CharField(choices=[('none', 'Aucun appel'), ('waiting', 'En attente que le médecin démarre'), ('ongoing', 'Appel en cours'), ('ended', 'Appel terminé')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='call_type',
            field=models.CharField(blank=True, choices=[('video', 'Vidéo'), ('audio', 'Audio')], help_text="Vidéo ou audio, uniquement si type='video' (consultation en ligne)", max_length=10, null=True),
        ),
    ]
