# Generated by Django 6.0.3 on 2026-07-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_call_ended_at_appointment_call_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_call_type',
            field=models.CharField(blank=True, choices=[('video', 'Vidéo'), ('audio', 'Audio')], help_text="Préférence indicative du patient à la réservation — le médecin garde la main au moment de l'appel.", max_length=10, null=True),
        ),
    ]
