# Generated by Django 6.0.3 on 2026-07-14 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_preferred_call_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage de la confirmation d'arrivée par le personnel hospitalier.", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text="Membre du personnel (médecin ou compte hôpital) ayant confirmé l'arrivée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token unique encodé dans le QR code du patient — jamais affiché en clair modifiable.', unique=True),
        ),
    ]
