# Generated by Django 6.0.3 on 2026-07-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du service (ex: Cardiologie)', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('consultation_fee', models.DecimalField(decimal_places=0, default=0, help_text='Tarif de consultation en XAF', max_digits=10)),
                ('duration', models.CharField(default='30 min', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopital_services', to='accounts.hospital')),
            ],
            options={
                'verbose_name': 'Service hospitalier',
                'verbose_name_plural': 'Services hospitaliers',
                'ordering': ['-created_at'],
            },
        ),
    ]
