# Generated by Django 6.0.3 on 2026-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='registration_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
